### ISSUE TITLE
Alternative form of communication

### ISSUE THREAD

**Issue by ivanperez-keera** [tomjaguarpaw/Arrows2#7]
I have been subscribed to this repo since it was created, I think, but I don't think there's been a lot of activity.

I find the async communication based on issues difficult for R&D.

For me, I think a better form of communication would be to have an initial kickoff meeting online via e.g., google meet, try all together to decide how to approach it, and then take it from there through a combination of delegation, regular meetings, and potentially even subgroups if we have quorum.

I'd like to propose that we do it that way. What do you all think?

**Comment by tomjaguarpaw** [comment]
I would be happy to participate in a video call if you think it would be helpful to inspire you!  (All the more so if you can take charge of organising it :))

**Comment by ivanperez-keera** [comment]
I suggest we hold the first video call maybe in 2 weeks.

Would that work?

**Comment by tomjaguarpaw** [comment]
Yes, I think so, although a more precise time will allow me to make a more precise answer!
